<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC273975" name="com.charter.test.MyServices1" tests="1" failures="1" timestamp="26 Dec 2014 12:35:52 GMT" time="0.000" errors="0">
  <testcase name="TD06_MyServices_Validate_UpdateAndSaveMACAddress" time="0.000" classname="com.charter.test.MyServices1">
    <failure type="java.lang.RuntimeException" message="java.lang.RuntimeException: java.lang.RuntimeException: Data not supplied for TD06_MyServices_Validate_UpdateAndSaveMACAddress">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Data not supplied for TD06_MyServices_Validate_UpdateAndSaveMACAddress
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Data not supplied for TD06_MyServices_Validate_UpdateAndSaveMACAddress
	at com.charter.utils.DataProviderClass.getDataFromFile(DataProviderClass.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 20 more
Caused by: java.lang.RuntimeException: Data not supplied for TD06_MyServices_Validate_UpdateAndSaveMACAddress
	at com.charter.utils.DataProviderClass.getDataFromFile(DataProviderClass.java:29)
	... 26 more
]]>
    </failure>
  </testcase> <!-- TD06_MyServices_Validate_UpdateAndSaveMACAddress -->
</testsuite> <!-- com.charter.test.MyServices1 -->
